In [ ]:
#MRO
class A:pass
class B:pass
class C:pass
class D:pass
class E:pass
class K1(C,A,B):pass
class K3(A,D):pass
class K2(B,D,E):pass
class Z(K1,K3,K2):pass
MRO of Z

In [7]:
#Numpy
#1D Array
import numpy as np
x=np.arange(5)
print(x)
y=np.array([1,2,3])
print(y)
#indexing
print(y[1])

[0 1 2 3 4]
[1 2 3]
2


In [13]:
#2D Array
import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)
y=np.array([[1,2],[4,5],[6,7]])
print(y)
#indexing
print(y[0][1])
print(x[-2][-2])
#slicing
x[1:,:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [6 7]]
2
5


array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
#3d Array
import numpy as np
x=np.arange(1,9).reshape(2,2,2)
print(x)
y=np.array([[[1,2],[4,5],[6,7]],
            [[8,9],[10,11],[12,13]]
           ])
print(y)
#indexing
print(y[0][1][0])
print(x[-2][-2][-2])
#slicing
x[1:,:,:]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[ 1  2]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]]]
4
1


array([[[5, 6],
        [7, 8]]])

In [16]:
#concatenationation

In [19]:
#nditer
import numpy as np
x=np.arange(1,9).reshape(2,2,2)
print(x)
for i in np.nditer(x[1:,:,:]):
    print(i)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
5
6
7
8


In [24]:
#odd row and odd column
import numpy as np
x=np.arange(1,10).reshape(3,3)
for i in np.nditer(x[1::2,::2]):
    print(i)

4
6
