In [4]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(np.where(x>3))
#output [rows] , dtype int, [columns]

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


In [5]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(np.where(x>4,"c8","A6"))

[['A6' 'A6' 'A6']
 ['A6' 'A6' 'c8']
 ['c8' 'c8' 'c8']]


In [18]:
import numpy as np
import random
x=np.random.randint(100,size=(5,5))
print(x)
print(np.where(x>50))

[[52 10 27 71  4]
 [27 51 67  1  6]
 [89 78 73  0 39]
 [ 2 96 78 83 48]
 [75 20 13 83 86]]
(array([0, 0, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int64), array([0, 3, 1, 2, 0, 1, 2, 1, 2, 3, 0, 3, 4], dtype=int64))


In [19]:
import numpy as np
import random
x=np.random.randint(2,20)
print(x)

16


In [20]:
#10x10 with 0 and 1 only
import numpy as np
import random
x=np.random.randint(2,size=(10,10))
print(x)

[[0 1 0 1 1 1 0 1 1 0]
 [0 1 1 0 0 0 1 0 1 1]
 [0 1 0 1 0 1 1 1 0 1]
 [1 1 1 1 0 1 1 1 1 0]
 [1 1 0 1 1 0 1 0 1 0]
 [1 0 1 1 0 0 1 1 1 0]
 [0 1 1 1 0 0 1 0 1 1]
 [0 0 1 1 0 0 0 1 1 0]
 [1 1 1 1 0 1 0 1 0 0]
 [0 0 1 0 0 1 0 1 1 0]]


In [25]:
#10x10 with 1 only
import numpy as np
x=np.zeros((10,10),dtype=int)
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [26]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(np.where(x>4,0,1))

[[1 1 1]
 [1 1 0]
 [0 0 0]]


In [28]:
#3x3 with 1 only
import numpy as np
x=np.ones((3,3),dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [30]:
import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)
print(np.max(x,axis=0))
print(np.max(x,axis=1))
print(np.min(x,axis=0))
print(np.min(x,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[3 6 9]
[1 2 3]
[1 2 3]


In [43]:
#688
import numpy as np
F=np.array([0, 12, 45.21, 34, 99.91, 32])
C=5*F/9-5*32/9
print(F)
print(C)
d=np.sort(C)
print(d)
print(np.where(d==0.))

[ 0.   12.   45.21 34.   99.91 32.  ]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778
   0.        ]
[-17.77777778 -11.11111111   0.           1.11111111   7.33888889
  37.72777778]
(array([2], dtype=int64),)


In [44]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
x=arr.reshape(2,-1)
y=arr.reshape(2,2,-1)
print(x)
print(y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [47]:
import numpy as np
x=np.arange(1,11)
y=np.array_split(x,4)
print(y)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


In [52]:
import numpy as np
x=np.arange(1,10).reshape(3,3)
y=np.array_split(x,2)
print(y)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [58]:
import numpy as np
x=np.arange(1,13).reshape(2,3,2)
y=np.array_split(x,3)
print(y)

[array([[[1, 2],
        [3, 4],
        [5, 6]]]), array([[[ 7,  8],
        [ 9, 10],
        [11, 12]]]), array([], shape=(0, 3, 2), dtype=int32)]


In [70]:
#2d array randomnly array sort only second row
import numpy as np
import random
x=np.random.randint(20,size=(3,3))
print(x)
y=np.sort(x[1])
x[1]=y
print(x)

[[5 0 5]
 [5 9 5]
 [4 1 1]]
[[0 5 5]
 [5 5 9]
 [1 1 4]]


In [75]:
#2d array randomnly array column wise
import numpy as np
import random
x=np.random.randint(10,size=(3,3))
print(x)
y=np.sort(x,0)
print(y)

[[4 7 3]
 [3 9 4]
 [5 6 7]]
[[3 6 3]
 [4 7 4]
 [5 9 7]]


In [78]:
#2d array randomnly array row wise
import numpy as np
import random
x=np.random.randint(10,size=(3,3))
print(x)
y=np.sort(x,1)
print(y)

[[7 3 4]
 [0 1 3]
 [6 4 0]]
[[3 4 7]
 [0 1 3]
 [0 4 6]]


In [81]:
import numpy as np
x=np.array([1,2,3,4,5])
np.append(x,2)


array([1, 2, 3, 4, 5, 2])

In [ ]:
import numpy as np
class Attendance:
    l1=[]
    def low(self,l):
        l1.append(l)
    def lowatt(self):
        print(self.l1)
        
class student(Attendance):
    ps=0
    python=0
    fsd=0
    de=0
    name=""
    l=[]
    def attendance(self):
        x=input("Enter name of student")
        self.name=x
        for i in (0,5,1):
            print("day",i)
            p1=int(input("Enter o for absent and 1 for present for ps"))
            self.ps+=p1
            p2=int(input("Enter o for absent and 1 for present for python"))
            self.python+=p1
            p3=int(input("Enter o for absent and 1 for present for fsd"))
            self.fsd+=p1
            p4=int(input("Enter o for absent and 1 for present for de"))
            self.de+=p1
        if((p1+p2+p3+p4)<15):
            self.l.append([self.name,(p1+p2+p3+p4)])
            super().low(self.l)
        
a=Attendance() 
s=student()
n=int(input("Enter no of students "))
for i in range(0,n):
    s.attendance()
s.lowatt()